export const types = {
  OPEN_SIDEBAR: 'OPEN_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  SET_SIDEBAR_INDEX: 'SET_SIDEBAR_INDEX',
  OPEN_HEADER_MENU: 'OPEN_HEADER_MENU',
  CLOSE_HEADER_MENU: 'CLOSE_HEADER_MENU',
}